# general settings
name: SwinIR_x5_wind_speed
model_type: SwinIRModel
scale: 5
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CustomDataset
    type: NumpyPairedDataset # 사용자 정의 데이터셋 클래스 이름
    dataroot_gt: /home/wj/works/Wind_Speed_Data/new_data/HR/train_hr.npy # HR 데이터 경로
    dataroot_lq: /home/wj/works/Wind_Speed_Data/new_data/LR/train_lr.npy # LR 데이터 경로
    #meta_info_file: basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt
    filename_tmpl: '{}'
    io_backend:
      type: numpy

    gt_size: 100
    use_hflip: false
    use_rot: false

    # data loader
    num_worker_per_gpu: 12
    batch_size_per_gpu: 32 # 배치사이즈 4
    dataset_enlarge_ratio: 1 # 데이터 증강 X
    prefetch_mode: ~

  val:
    name: CustomValDataset
    type: NumpyPairedDataset # 검증 데이터셋도 같은 구조 사용
    dataroot_gt: /home/wj/works/Wind_Speed_Data/new_data/HR/val_hr.npy
    dataroot_lq: /home/wj/works/Wind_Speed_Data/new_data/LR/val_lr.npy
    io_backend:
      type: numpy

# network structures
network_g:
  type: SwinIR
  upscale: 5 # 4->5
  in_chans: 1 # 3->1
  img_size: 20 # 수정
  window_size: 5 # 20/5=4로 나눠지고, 100도 5의 배수
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'nearest+conv'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [43750, 65625, 78750, 83125] # 50%, 75%, 90%, 95%에서 학습률 감소
    gamma: 0.5

  total_iter: 87500 # 100에포크
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1.75e4 # 20 에포크마다 검증
  save_img: true

  metrics:
    rmse: # metric name, can be arbitrary
      type: calculate_rmse
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1.75e4 # 20 에포크마다 체크포인트 저장
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
